# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np

In [6]:
x = np.random.random((3,3,3))
print('3x3x3 Array:\n')
print(x)

3x3x3 Array:

[[[0.9291282  0.67106174 0.32546316]
  [0.95123442 0.36373359 0.35225532]
  [0.04740841 0.23466665 0.71389072]]

 [[0.32458835 0.5136954  0.32650718]
  [0.3556016  0.96709065 0.43078438]
  [0.69925679 0.24943596 0.35092015]]

 [[0.87622213 0.99078766 0.82696437]
  [0.43291104 0.61181405 0.29115736]
  [0.68731108 0.9359512  0.86152412]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [7]:
matrix = np.zeros((5,5))
matrix = np.diag(1+np.arange(4),k = -1)
print('Matrix with 1,2,3,4 just below Diagonal:\n\n', matrix)

Matrix with 1,2,3,4 just below Diagonal:

 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [9]:
x = np.zeros((8,8), dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print('Check Borad Pattern:\n')
print(x)

Check Borad Pattern:

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [11]:

x= np.random.randn(5,5)
print("Original Array:\n")
print(x)

xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)

print("\nAfter normalization:\n")
print(x)

Original Array:

[[-0.23632073 -0.11583989 -0.02703334  0.31744144 -0.94110304]
 [-0.1904471   0.46014783  0.52270332  1.28876174 -1.35850412]
 [ 0.18545113  0.83419247  1.20427897  0.08484585  0.93623192]
 [ 0.17490511  0.17509915  1.89808928 -1.07150462  0.26527706]
 [-0.25509644 -1.35899265 -0.75164562  1.44897517  0.18664767]]

After normalization:

[[3.44686425e-01 3.81676848e-01 4.08942526e-01 5.14704305e-01
  1.28301844e-01]
 [3.58770696e-01 5.58518490e-01 5.77724482e-01 8.12922257e-01
  1.49992572e-04]
 [4.74180208e-01 6.73358906e-01 7.86984079e-01 4.43292044e-01
  7.04687394e-01]
 [4.70942334e-01 4.71001907e-01 1.00000000e+00 8.82655207e-02
  4.98688627e-01]
 [3.38921845e-01 0.00000000e+00 1.86469681e-01 8.62111511e-01
  4.74547571e-01]]


# 5.  How to find common values between two arrays?

In [15]:
array1 = np.array([0, 10, 20, 40, 60])
array2 = [10, 30, 40]
print("Array1: ", array1)
print("Array2: ", array2)
print("Common values between two arrays:", np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays: [10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [16]:
import datetime as dt

today = dt.date.today()
yesterday = today - dt.timedelta(days = 1)
tomorrow = today + dt.timedelta(days = 1) 

print('Yesterday: ',yesterday)
print('Today: ', today)
print('Tomorrow: ', tomorrow)

Yesterday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [17]:
a = np.array([[1,23,5],[6,9,40]])
b =  np.array([[1,23,5],[6,9,40]])
print('Array1:\n', a)
print('Array2:\n', b)
print('\nResult is True if the Arrays are Equal \nResult is False if the Arrays are Not Equal ')
np.array_equal(a,b)

Array1:
 [[ 1 23  5]
 [ 6  9 40]]
Array2:
 [[ 1 23  5]
 [ 6  9 40]]

Result is True if the Arrays are Equal 
Result is False if the Arrays are Not Equal 


True

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [18]:
vector = np.array([1,45,867,90,48,94,100,166,867,110])
print('Vector: ', vector)
print('Length of Vector: ', len(vector))

vector_max = vector.max() 
print('Maximum value:', vector_max)
index= np.where(vector == vector_max)
vector[index] = 0

print('Replacing {} by 0: {}'.format(vector_max, vector))


Vector:  [  1  45 867  90  48  94 100 166 867 110]
Length of Vector:  10
Maximum value: 867
Replacing 867 by 0: [  1  45   0  90  48  94 100 166   0 110]


# 9. How to print all the values of an array?

In [19]:
 #1-D Array :
print('For 1-D Array:')
x = np.array([12, 34, 67, 89])
for i in range(len(x)):
    print(f"The element at index {i} is: {x[i]}")

# 2-D Array: 
print('\nFor 2-D Array:')
y = np.array([[13,57,45],[34,76,88],[92,21,19],[98,67,0]])
for i in range(len(y)):
    print(f"The element at index {i} is: {y[i]}")

For 1-D Array:
The element at index 0 is: 12
The element at index 1 is: 34
The element at index 2 is: 67
The element at index 3 is: 89

For 2-D Array:
The element at index 0 is: [13 57 45]
The element at index 1 is: [34 76 88]
The element at index 2 is: [92 21 19]
The element at index 3 is: [98 67  0]


# 10.Subtract the mean of each row of a matrix

In [20]:
arr = np.array([[1, 100, 0, 0], [2, 110, 0, 0], [3, 120, 0, 0]])
print('Initial Array:\n', arr)
print('Mean of Each row: ',arr.mean(axis=1))
mean = arr - arr.mean(axis=1, keepdims=True) 
print('\nResultant Matrix After Subtracting Mean:\n',mean)

Initial Array:
 [[  1 100   0   0]
 [  2 110   0   0]
 [  3 120   0   0]]
Mean of Each row:  [25.25 28.   30.75]

Resultant Matrix After Subtracting Mean:
 [[-24.25  74.75 -25.25 -25.25]
 [-26.    82.   -28.   -28.  ]
 [-27.75  89.25 -30.75 -30.75]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [21]:

Z = np.ones(10)
print("Initial Vector:\n",Z)
I = np.random.randint(0, len(Z),20)
print("Random Values:\n",I)
Z += np.bincount(I, minlength=len(Z))
print("Resultant Vector:\n",Z)

Initial Vector:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Random Values:
 [5 8 7 1 0 1 2 5 3 8 6 0 8 7 3 5 9 8 9 1]
Resultant Vector:
 [3. 4. 2. 3. 1. 4. 2. 3. 5. 3.]


# 12.How to get the diagonal of a dot product?

In [14]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))

print("Array A:\n", A)
print("Array B:\n", B)

print('\nDot product:\n',np.dot(A,B))
dot = np.diag(np.dot(A, B))
print('\nThe Diagonal Elements are:\n', dot)

Array A:
 [[1 9 8]
 [1 9 0]
 [6 1 9]]
Array B:
 [[8 2 8]
 [9 2 1]
 [2 5 9]]

Dot product:
 [[105  60  89]
 [ 89  20  17]
 [ 75  59 130]]

The Diagonal Elements are:
 [105  20 130]


# 13.How to find the most frequent value in an array?

In [13]:
Z = np.random.randint(0,10,30)
print ("Array:", Z)
print('Most Frequent Value:', np.bincount(Z).argmax())

Array: [6 9 8 8 7 9 1 8 5 5 2 0 9 4 2 4 9 1 3 0 5 9 4 9 5 3 8 3 7 5]
Most Frequent Value: 9


# 14.How to get the n largest values of an array

In [12]:
Z = np.arange(100)
np.random.shuffle(Z)
n = int(input('Enter the value of n: '))
print(f"{n} Largest values in array: ", Z[np.argsort(Z)[-n:]])

Enter the value of n: 665
665 Largest values in array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


# 15.How to create a record array from a regular array?

In [23]:
print('For a Single Array:\n')
x3 = np.array([['Riya',98, 99],['sahil', 90, 92],['anikt', 89, 90]])

print('Regular Array:\n', x3)
rec = np.core.records.fromarrays(x3.T,names='name,mks1,mks2',formats='S80, i8, i8') # The arrays are now transposed'

print('\nRecord Array:', rec)
print('Type of Result:', type(rec))

For a Single Array:

Regular Array:
 [['Riya' '98' '99']
 ['sahil' '90' '92']
 ['anikt' '89' '90']]

Record Array: [(b'Riya', 98, 99) (b'sahil', 90, 92) (b'anikt', 89, 90)]
Type of Result: <class 'numpy.recarray'>


In [22]:
x1 = np.array([1,2,3,4])
x2 = np.array(['R','I','Y','A'])

print('Regular Array 1:',x1)
print('Regular Array 2:',x2)

records = np.core.records.fromarrays([x1,x2], names='Col1, Col2') # The arrays are now transposed 

print('\nRecord Array:', records)
print('Type of Result:', type(records))

Regular Array 1: [1 2 3 4]
Regular Array 2: ['R' 'I' 'Y' 'A']

Record Array: [(1, 'R') (2, 'I') (3, 'Y') (4, 'A')]
Type of Result: <class 'numpy.recarray'>
